### ISSUE TITLE
Any issues using implementing your bot?

### ISSUE THREAD

**Issue by Stevenic** [wballard/botbuilder-hipchat#1]
Nice :) Just wondering if you ran into any issues getting your bot to work? I see that you're using the Session object directly which is the more flexible way to go. The Session object (and the Bots for that matter) are still evolving so breaking changes may creep in, especially for the Session object. I'll try to give you a heads up if I end up breaking something. 

I added a new minSendDelay property to the Session object which you may want to support. This lets you adjust the rate at which the bot replies to a user.

I see you implemented listen(). Are you planning to implement beginDialog() as well? That method lets the bot initiate a conversation with the user proactively.

Nice job...

Steve

**Comment by Stevenic** [comment]
I just added a [Other Platforms](http://docs.botframework.com/builder/node/bots/other-platforms) section to the docs to track 3rd party connectors like yours.

**Comment by wballard** [comment]
Yes - using just Session makes the API a bit 'less redundant' in particularly around beginDialog. I didn't have a case for bot-initiated just yet in my implementation, is there an example or test bot you can link me so I can hook that up?

Overall -- this was a pretty easy adapt, the botbuilder API is great, I spent far more time hunting down XMPP implementation details for HipChat -- though the HipChat dev team is across the street here in Austin, so I should probably take more advantage of that!

I also flattened this out to be a bit more conventional/promise style. RXJS is great, but most of my staff isn't familiar with it.
