### ISSUE TITLE
Upgrading to v3 of SDK

### ISSUE THREAD

**Issue by Stevenic** [wballard/botbuilder-hipchat#4]
Hey there... Just wondering if you have plans to upgrade this to the new v3 SDK?  In the new SDK you're HipchatBot would become a HipchatConnector for the new UniversalBot class and it should be way simpler as all you have to do is the schema mapping work. The UniversalBot class does all of the session management now.  If you're up for doing the work to port your lib to the new connector model I'm happy to answer any questions and code review your final bits.

Steve

**Comment by wballard** [comment]
Love to. I'll give it a go and let you know what questions I have.

**Comment by Stevenic** [comment]
Thanks

**Comment by wballard** [comment]
We're actually planning on switching to MS Teams and just use the framework support. Looking forward to it.
